const fs = require('fs')

try{

}catch(err){
    console.error(err);
}