const fs = require('fs')

try{
    
}catch(err){
    console.log(err);
}